package ipproject;



import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author submisra
 */
public class DestinationSelection extends javax.swing.JFrame {

    private int JourneyId = 0;
    /**
     * Creates new form DestinationSelection
     */
    public DestinationSelection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        from1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        to1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        data = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        seats = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        net_fare = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHOOSE YOUR DESTINATION");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(230, 10, 430, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("From:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 90, 80, 30);

        from1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        from1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Raipur", "Nagpur", "Mumbai", "Pune", "Bhilai" }));
        jPanel1.add(from1);
        from1.setBounds(100, 130, 140, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("To:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(480, 100, 80, 20);

        to1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        to1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Raipur", "Nagpur", "Mumbai", "Pune", "Bhilai" }));
        jPanel1.add(to1);
        to1.setBounds(440, 130, 170, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Date of Travel ( DD/MON/YYYY )");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 200, 240, 30);

        data.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        data.setText("Proceed To Payment");
        data.setEnabled(false);
        data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataActionPerformed(evt);
            }
        });
        jPanel1.add(data);
        data.setBounds(260, 420, 310, 40);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(50, 250, 190, 30);

        jButton1.setText("View Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(680, 440, 100, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("No. Of Seats:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(360, 230, 110, 30);

        seats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        seats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatsActionPerformed(evt);
            }
        });
        jPanel1.add(seats);
        seats.setBounds(490, 230, 100, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Net Fare:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(280, 330, 70, 20);
        jPanel1.add(net_fare);
        net_fare.setBounds(370, 320, 100, 30);

        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lighthouse.jpg"))); // NOI18N
        jLabel6.setText("FRom");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 820, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataActionPerformed

        // TODO add your handling code here:
         
         String query = "";
         String From= from1.getSelectedItem().toString();
         String To= to1.getSelectedItem().toString();
         String date1=jTextField1.getText();
         String lUsername= ToursUtil.getUsername();
         String no_of_seats= seats.getSelectedItem().toString();
         double fareTf;
         fareTf= Double.parseDouble(net_fare.getText());
         
        try
        {
        Connection con =  mySqlDBConnection.getConnection();
        Statement stmt = (Statement) con.createStatement();
        
        query="INSERT INTO Journey(From_,To_, Date_Of_Journey, Username, No_of_seats,fare) VALUES ('"+From+"', '"+To+"', '"+date1+"', '"+lUsername+"', '"+no_of_seats+"' , '"+fareTf+"')";
        stmt.executeUpdate(query);
        
        query = "SELECT LAST_INSERT_ID()";
        ResultSet rs = stmt.executeQuery(query);
        rs.next();
        JourneyId =rs.getInt(1);
        System.out.println(JourneyId);
        
        new modePayment(JourneyId).setVisible(true);
        this.dispose();        
        
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
       
          
           
    }//GEN-LAST:event_dataActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new View_details().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void seatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatsActionPerformed
        // TODO add your handling code here:
       data.setEnabled(true);
        int no;
        double a;
        no=seats.getSelectedIndex()+1;
        a=no*650;
        net_fare.setText(Double.toString(a));
        
        data.setVisible(true);
    }//GEN-LAST:event_seatsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DestinationSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DestinationSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DestinationSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DestinationSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DestinationSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton data;
    private javax.swing.JComboBox<String> from1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField net_fare;
    private javax.swing.JComboBox<String> seats;
    private javax.swing.JComboBox<String> to1;
    // End of variables declaration//GEN-END:variables
}
